In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
X = df.drop("sales",axis=1)
y = df[["sales"]]

In [8]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [9]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
# Statsmodel ile model kurmak 
import statsmodels.api as sm

In [11]:
lm = sm.OLS(y,X)

In [12]:
model = lm.fit()

In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Tue, 11 Jan 2022   Prob (F-statistic):                   2.43e-171
Time:                        12:14:05   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
## Sci-kit ile model kurmak 
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [16]:
model=lm.fit(X,y)

In [17]:
model.intercept_

array([2.93888937])

In [18]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [20]:
#Tahmin
# * Sales = 2.94 + TV 0.04 + radio0.19-newspaper0.001

In [21]:
2.94 + 30*0.04+10*0.19-40*0.001

5.999999999999999

In [22]:
yeni_veri = [[30],[10],[40]]

In [23]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [24]:
yeni_veri

0   1   2
0  30  10  40

In [25]:
model.predict(yeni_veri)

/Users/cgncvk/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [28]:
mse = mean_squared_error(y,model.predict(X))

In [29]:
rmse = np.sqrt(mse)

In [30]:
mse

2.7841263145109365

In [31]:
rmse

1.66857014072257

In [32]:
#Ç.D.R Model Tuning (Doğrulama)
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [33]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [34]:
# Test-train split
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=99)

In [36]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [37]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [38]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [39]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [40]:
lm = LinearRegression()

In [41]:
model=lm.fit(X_train,y_train)

In [42]:
np.sqrt(mean_squared_error(y_train,model.predict(X_train))) # Eğitim hatası

1.723682482265075

In [43]:
np.sqrt(mean_squared_error(y_test,model.predict(X_test))) # Test hatası

1.4312783138301641

In [44]:
# K-Fold CV 
from sklearn.model_selection import cross_val_score

In [45]:
cross_val_score(model,X_train,y_train,cv=10,scoring = "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [46]:
np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring = "neg_mean_squared_error"))

3.317028974234126

In [47]:
#rmse
np.sqrt(np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring = "neg_mean_squared_error")))

1.8212712522395245